# Generated by Django 4.0.5 on 2023-02-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('project_access', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default=0, max_length=7)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('recent_execution_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleExecution',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=200, verbose_name='software version')),
                ('total_time', models.FloatField(verbose_name='time total')),
                ('test_total', models.IntegerField(verbose_name='tests total')),
                ('tests_passed', models.IntegerField(verbose_name='tests passed')),
                ('tests_failed', models.IntegerField(verbose_name='tests failed')),
                ('tests_skipped', models.IntegerField(verbose_name='tests skipped')),
                ('date_executed', models.DateTimeField(auto_now=True)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='prject')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseObject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='test case name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('suite_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singleexecution')),
            ],
        ),
        migrations.CreateModel(
            name='SingleTestResult',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('SKIP', 'SKIP')], max_length=4)),
                ('test_time', models.FloatField(verbose_name='execution time')),
                ('error_message', models.CharField(blank=True, max_length=1024, null=True)),
                ('suite_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singleexecution')),
                ('tag', models.ManyToManyField(blank=True, default=None, null=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='SingleSuiteResult',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('test_status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('SKIP', 'SKIP')], max_length=4)),
                ('total_time', models.FloatField()),
                ('test_total', models.IntegerField()),
                ('tests_passed', models.IntegerField()),
                ('tests_failed', models.IntegerField()),
                ('tests_skipped', models.IntegerField()),
                ('suite_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singleexecution')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_access', models.ManyToManyField(to='core.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singletestresult')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
